import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import GlobalLoader from "./loading";
import ClientRoot from "./client-root";

export const metadata: Metadata = {
  title: "Mini system",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Battambang:wght@100;300;400;700;900&family=Moul&family=Public+Sans:ital,wght@0,100..900;1,100..900&family=Siemreap&display=swap"
          rel="stylesheet" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
          rel="stylesheet" />
      </head>

      <body>
        
        <div className="bg-white text-black dark:bg-gray-900 dark:text-white">
          <ClientRoot >
          <ThemeProvider attribute="class" defaultTheme="light">
             <GlobalLoader />
            {children}
          </ThemeProvider>
          </ClientRoot>
        </div>
      </body>

    </html>
  );
}